
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuefnsfzyneciyaucwrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1ZWZuc2Z6eW5lY2l5YXVjd3JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NzgzNTgsImV4cCI6MjA1NzI1NDM1OH0.ZusnFKNlgH6hHMU8g5UkjnUwwmQn340EnHCQYPNy_ZI";

// Database name: ecoscoot
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
